name: CI/CD

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: touch ./src/main/resources/application.yml
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
      - run: cat ./src/main/resources/application.yml
      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          java-package: jdk
          distribution: zulu

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          ./gradlew build

      - name: Checkout
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.TOKEN }}
          submodules: recursive
