# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI/CD

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: touch ./src/main/resources/application.yml
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
      - run: cat ./src/main/resources/application.yml
      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          java-package: jdk
          distribution: zulu
      - name: Set execute permission on gradlew
        run: chmod +x gradlew

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          ./gradlew build

      - name: Checkout
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.TOKEN }}
          submodules: recursive


